/**
 * Centralized Seed Data for Dinasari Food Courier (DFC).
 *
 * Shared between Admin Web and Mobile applications for full-fidelity
 * standalone operation without a connected remote database.
 */

import { toPaise } from './money';
import type { Product } from './catalogue';
import type { Order, Rider } from './types';

const now = Date.now();
const min = 60 * 1000;

export const SEED_RIDERS: Rider[] = [
  {
    uid: 'rider-1',
    name: 'A. Dhanush',
    phone: '+919876500004',
    isOnline: true,
    activeOrderId: 'seed-1044',
    cancellationsToday: 0,
    maxDailyCancellations: 2,
    cancellationHistory: [],
  },
  {
    uid: 'rider-2',
    name: 'K. Karthik',
    phone: '+919876500005',
    isOnline: true,
    activeOrderId: null,
    cancellationsToday: 1,
    maxDailyCancellations: 2,
    cancellationHistory: [
      {
        orderId: 'seed-1038',
        orderCode: 1038,
        timestamp: now - 3 * 60 * min,
        reason: 'Heavy rain flooded road in Sellur',
        explanation: 'Water level reached silencer, waited for water to recede',
      },
    ],
  },
  {
    uid: 'rider-3',
    name: 'S. Vijay',
    phone: '+919876500006',
    isOnline: false,
    activeOrderId: null,
    cancellationsToday: 3,
    maxDailyCancellations: 2,
    isOfflineDueToCancellations: true,
    cancellationHistory: [
      {
        orderId: 'seed-1021',
        orderCode: 1021,
        timestamp: now - 5 * 60 * min,
        reason: 'Tyre puncture near Goripalayam junction',
        explanation: 'Took 45 mins to find a mechanic shop',
      },
    ],
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-ghee-podi-idli',
    storeId: 'murugan-idli-shop',
    name: 'Ghee Podi Idli (2 pcs)',
    nameTa: 'நெய் பொடி இட்லி (2 எண்ணிக்கை)',
    category: 'food',
    sellPaise: toPaise(90),
    mrpPaise: toPaise(90),
    stockQty: 50,
    lowStockAt: 10,
    isActive: true,
    unit: 'plate',
    updatedAt: now,
  },
  {
    id: 'prod-plain-idli',
    storeId: 'murugan-idli-shop',
    name: 'Steamed Idli (2 pcs)',
    nameTa: 'மல்லிகைப் பூ இட்லி (2 எண்ணிக்கை)',
    category: 'food',
    sellPaise: toPaise(50),
    mrpPaise: toPaise(50),
    stockQty: 80,
    lowStockAt: 15,
    isActive: true,
    unit: 'plate',
    updatedAt: now,
  },
  {
    id: 'prod-bun-parotta',
    storeId: 'simmakkal-konar-mess',
    name: 'Madurai Special Bun Parotta',
    nameTa: 'மதுரை ஸ்பெஷல் பன் பரோட்டா',
    category: 'food',
    sellPaise: toPaise(45),
    mrpPaise: toPaise(45),
    stockQty: 100,
    lowStockAt: 20,
    isActive: true,
    unit: 'pc',
    updatedAt: now,
  },
  {
    id: 'prod-mutton-kari-dosa',
    storeId: 'simmakkal-konar-mess',
    name: 'Mutton Kari Dosa',
    nameTa: 'மட்டன் கறி தோசை',
    category: 'food',
    sellPaise: toPaise(240),
    mrpPaise: toPaise(250),
    stockQty: 30,
    lowStockAt: 5,
    isActive: true,
    unit: 'plate',
    updatedAt: now,
  },
  {
    id: 'prod-jigarthanda-special',
    storeId: 'famous-jigarthanda',
    name: 'Special Basundi Jigarthanda',
    nameTa: 'ஸ்பெஷல் பாசுந்தி ஜிகர்தண்டா',
    category: 'food',
    sellPaise: toPaise(80),
    mrpPaise: toPaise(80),
    stockQty: 60,
    lowStockAt: 10,
    isActive: true,
    unit: 'glass',
    updatedAt: now,
  },
  {
    id: 'prod-sona-masoori-rice',
    storeId: 'amma-mini-mart',
    name: 'Sona Masoori Rice (5kg)',
    nameTa: 'சோனா மசூரி அரிசி (5 கிலோ)',
    category: 'grocery',
    sellPaise: toPaise(320),
    mrpPaise: toPaise(350),
    stockQty: 25,
    lowStockAt: 5,
    isActive: true,
    unit: 'bag',
    updatedAt: now,
  },
  {
    id: 'prod-malligai-poo',
    storeId: 'simmakkal-flowers',
    name: 'Madurai Malligai (2 muzham)',
    nameTa: 'மதுரை மல்லிகை (2 முழம்)',
    category: 'grocery',
    sellPaise: toPaise(60),
    mrpPaise: toPaise(70),
    stockQty: 40,
    lowStockAt: 8,
    isActive: true,
    unit: 'pack',
    updatedAt: now,
  },
];

export const SEED_ORDERS: Order[] = [
  {
    id: 'seed-1045',
    code: 1045,
    customerUid: 'cust-1',
    customerName: 'Anand Kumar',
    customerPhone: '+919876543210',
    localityId: 'kk-nagar',
    addressLine: '14, 80 Feet Road, Near Apollo Hospital',
    category: 'food',
    status: 'incoming',
    items: [
      { id: 'i1', name: 'Ghee Podi Idli (2 pcs)', quantity: 3, unit: 'plate', unitPricePaise: toPaise(90), included: true, confidence: 1.0 },
      { id: 'i2', name: 'Medhu Vada', quantity: 2, unit: 'pc', unitPricePaise: toPaise(35), included: true, confidence: 1.0 },
    ],
    storeId: 'murugan-idli-shop',
    storeName: 'Murugan Idli Shop',
    riderUid: null,
    riderName: null,
    pricing: {
      itemsPaise: toPaise(340),
      deliveryPaise: toPaise(29),
      servicePaise: 0,
      totalPaise: toPaise(369),
    },
    paymentMode: 'cod',
    paymentStatus: 'unpaid',
    source: { kind: 'voice', transcript: 'Murugan Idli Shop-la rendu set Ghee Podi Idli, rendu Vada KK Nagar Apollo pakka.' },
    ai: null,
    deliveryOtp: '5821',
    timeline: [{ status: 'incoming', at: now - 4 * min, by: 'customer', note: 'Voice order parsed' }],
    createdAt: now - 4 * min,
    updatedAt: now - 4 * min,
  },
  {
    id: 'seed-1044',
    code: 1044,
    customerUid: 'cust-102',
    customerName: 'K. Rameshwaran',
    customerPhone: '+919876500102',
    localityId: 'simmakkal',
    addressLine: '82, North Veli Street',
    category: 'food',
    status: 'dispatched',
    items: [
      { id: 'i1', name: 'Madurai Special Bun Parotta', quantity: 4, unit: 'pc', unitPricePaise: toPaise(45), included: true, confidence: 1.0 },
      { id: 'i2', name: 'Mutton Kari Dosa', quantity: 1, unit: 'plate', unitPricePaise: toPaise(240), included: true, confidence: 1.0 },
    ],
    storeId: 'simmakkal-konar-mess',
    storeName: 'Simmakkal Konar Mess',
    riderUid: 'rider-1',
    riderName: 'A. Dhanush',
    pricing: {
      itemsPaise: toPaise(420),
      deliveryPaise: toPaise(35),
      servicePaise: 0,
      totalPaise: toPaise(455),
    },
    paymentMode: 'prepaid',
    paymentStatus: 'paid',
    source: { kind: 'text', transcript: '4 Bun Parotta and 1 Mutton Kari Dosa' },
    ai: null,
    deliveryOtp: '7412',
    timeline: [
      { status: 'incoming', at: now - 22 * min, by: 'customer' },
      { status: 'paid', at: now - 20 * min, by: 'gateway' },
      { status: 'vendor_accepted', at: now - 18 * min, by: 'vendor' },
      { status: 'packing', at: now - 12 * min, by: 'vendor' },
      { status: 'ready_for_pickup', at: now - 6 * min, by: 'vendor' },
      { status: 'dispatched', at: now - 2 * min, by: 'admin', note: 'Assigned to Captain Dhanush' },
    ],
    prepStartedAt: now - 18 * min,
    prepCompletedAt: now - 6 * min,
    actualPrepMinutes: 12,
    dispatchedAt: now - 2 * min,
    createdAt: now - 22 * min,
    updatedAt: now - 2 * min,
  },
  {
    id: 'seed-1043',
    code: 1043,
    customerUid: 'cust-103',
    customerName: 'P. Kavitha',
    customerPhone: '+919876500103',
    localityId: 'anna-nagar',
    addressLine: 'Plot 42, Kuruvikaran Salai',
    category: 'grocery',
    status: 'packing',
    items: [
      { id: 'i1', name: 'Sona Masoori Rice (5kg)', quantity: 1, unit: 'bag', unitPricePaise: toPaise(320), included: true, confidence: 1.0 },
      { id: 'i2', name: 'Madurai Malligai (2 muzham)', quantity: 2, unit: 'pack', unitPricePaise: toPaise(60), included: true, confidence: 1.0 },
    ],
    storeId: 'amma-mini-mart',
    storeName: 'Amma Mini Mart',
    riderUid: null,
    riderName: null,
    pricing: {
      itemsPaise: toPaise(440),
      deliveryPaise: toPaise(29),
      servicePaise: 0,
      totalPaise: toPaise(469),
    },
    paymentMode: 'cod',
    paymentStatus: 'unpaid',
    source: { kind: 'photo', mimeType: 'image/jpeg' },
    ai: null,
    deliveryOtp: '9103',
    timeline: [
      { status: 'incoming', at: now - 15 * min, by: 'customer' },
      { status: 'vendor_accepted', at: now - 12 * min, by: 'vendor' },
      { status: 'packing', at: now - 5 * min, by: 'vendor' },
    ],
    delayMinutes: 10,
    delayReason: 'Restocking fresh morning jasmine flowers',
    delayReportedAt: now - 4 * min,
    createdAt: now - 15 * min,
    updatedAt: now - 4 * min,
  },
  {
    id: 'seed-1042',
    code: 1042,
    customerUid: 'cust-1',
    customerName: 'Anand Kumar',
    customerPhone: '+919876543210',
    localityId: 'kk-nagar',
    addressLine: '14, 80 Feet Road, Near Apollo Hospital',
    category: 'food',
    status: 'delivered',
    items: [
      { id: 'i1', name: 'Special Basundi Jigarthanda', quantity: 2, unit: 'glass', unitPricePaise: toPaise(80), included: true, confidence: 1.0 },
    ],
    storeId: 'famous-jigarthanda',
    storeName: 'Famous Jigarthanda',
    riderUid: 'rider-1',
    riderName: 'A. Dhanush',
    pricing: {
      itemsPaise: toPaise(160),
      deliveryPaise: toPaise(25),
      servicePaise: 0,
      totalPaise: toPaise(185),
    },
    paymentMode: 'prepaid',
    paymentStatus: 'paid',
    source: { kind: 'text', transcript: '2 Special Basundi Jigarthanda' },
    ai: null,
    deliveryOtp: '1102',
    timeline: [
      { status: 'incoming', at: now - 90 * min, by: 'customer' },
      { status: 'delivered', at: now - 45 * min, by: 'rider', note: 'Handed to customer' },
    ],
    createdAt: now - 90 * min,
    updatedAt: now - 45 * min,
  },
];
