import { Captain, Order } from '@dfc/core';

export const DEMO_CAPTAINS: Captain[] = [
  {
    id: 'captain_001',
    name: 'Karthik',
    phone: '9876543210',
    status: 'OFFLINE',
    cancellationCount: 3,
    maxFreeCancellations: 3,
    vehicle: 'Bike',
    rating: 4.5,
    activeOrderId: null,
  },
  {
    id: 'captain_002',
    name: 'Arun',
    phone: '9876543211',
    status: 'ONLINE',
    cancellationCount: 0,
    maxFreeCancellations: 3,
    vehicle: 'Bike',
    rating: 4.8,
    activeOrderId: null,
  },
  {
    id: 'captain_003',
    name: 'Suresh',
    phone: '9876543212',
    status: 'OFFLINE',
    cancellationCount: 1,
    maxFreeCancellations: 3,
    vehicle: 'Bike',
    rating: 4.2,
    activeOrderId: null,
  },
];

export const DEMO_ORDERS: Order[] = [
  {
    id: 'order_1024',
    code: 1024,
    customerUid: 'cust_001',
    customerName: 'Sanjay Kumar',
    customerPhone: '9876543200',
    localityId: 'anna-nagar',
    addressLine: '12, 4th Cross Street, Anna Nagar',
    category: 'grocery',
    status: 'ready_for_pickup',
    items: [
      {
        id: 'item_1',
        name: 'Aashirvaad Atta',
        unit: '5 kg',
        quantity: 1,
        unitPricePaise: 25000,
        confidence: 0.9,
        included: true,
      },
    ],
    storeId: 'store_001',
    storeName: 'Anna Nagar Supermarket',
    riderUid: null,
    riderName: null,
    pricing: {
      itemsPaise: 25000,
      deliveryPaise: 3000,
      servicePaise: 0,
      totalPaise: 28000,
    },
    paymentMode: 'prepaid',
    paymentStatus: 'paid',
    source: {
      kind: 'text',
      transcript: '5kg Aashirvaad Atta',
    },
    ai: null,
    deliveryOtp: '123456',
    timeline: [
      { status: 'incoming', at: Date.now() - 3600000, by: 'customer' },
      { status: 'admin_review', at: Date.now() - 3500000, by: 'system' },
      { status: 'awaiting_payment', at: Date.now() - 3400000, by: 'admin' },
      { status: 'paid', at: Date.now() - 3000000, by: 'system' },
      { status: 'vendor_accepted', at: Date.now() - 2500000, by: 'vendor' },
      { status: 'packing', at: Date.now() - 2000000, by: 'vendor' },
      { status: 'ready_for_pickup', at: Date.now() - 1000000, by: 'vendor' },
    ],
    createdAt: Date.now() - 3600000,
    updatedAt: Date.now() - 1000000,
  },
];
